#!/usr/bin/env sh

for profile in {bash,compton,scripts,dunst,emacs,git,i3,i3blocks,info,mpd,rofi,vim,xorg,zsh}; do
  if stow $profile; then
    echo -e "[$(tput setaf 2)OK$(tput sgr0)]\t$profile"
  else
    echo -e "[$(tput setaf 1)ERROR$(tput sgr0)]\t$profile"
  fi
done

if [ ! -d ~/.vim/plugged ]; then
  if curl -fLo ~/.vim/autoload/plug.vim --create-dirs 'https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'; then
    echo -e "[$(tput setaf 2)OK$(tput sgr0)]\tvim-plugged"
  else
    echo -e "[$(tput setaf 1)ERROR$(tput sgr0)]\tvim-plugged"
  fi
fi

if [ ! -d ~/.zplug ]; then
  if curl -sL --proto-redir -all,https 'https://raw.githubusercontent.com/zplug/installer/master/installer.zsh | zsh'; then
    echo -e "[$(tput setaf 2)]OK$(tput sgr0)]\tzplug"
  else
    echo -e "[$(tput setaf 1)]ERROR$(tput sgr0)]\tzplug"
  fi
fi

if make -C UNSTOWABLE/st/ -f Makefile && sudo make -C UNSTOWABLE/st/ -f Makefile install; then
  echo -e "[$(tput setaf 2)OK$(tput sgr0)]\tst"
else
  echo -e "[$(tput setaf 1)ERROR$(tput sgr0)]\tst"
fi 
