#!/usr/bin/env sh

status_cmd() {
  if [ $1 = 0 ]; then
    echo -e "[$(tput setaf 2)OK$(tput sgr0)]\t$2"
  else
    echo -e "[$(tput setaf 1)ERROR$(tput sgr0)]\t$2"
  fi
}

for profile in {bash,compton,scripts,dunst,emacs,git,i3,i3blocks,info,mpd,rofi,vim,xorg,zsh}; do
  stow $profile
  status_cmd $? $profile
done

if [ ! -d ~/.vim/plugged ]; then
  curl -fLo ~/.vim/autoload/plug.vim --create-dirs 'https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  status_cmd $? "vim-plugged"
fi

if [ ! -d ~/.zplug ]; then
  curl -sL --proto-redir -all,https 'https://raw.githubusercontent.com/zplug/installer/master/installer.zsh | zsh'
  status_cmd $? "zplug"
fi

make -C UNSTOWABLE/st/ -f Makefile && sudo make -C UNSTOWABLE/st/ -f Makefile install
status_cmd $? "st"
